// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notes.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createNote = `-- name: CreateNote :one
INSERT INTO notes (owner_id, title, body) VALUES ($1, $2, $3) RETURNING id, owner_id, title, body, created_at, updated_at
`

type CreateNoteParams struct {
	OwnerID string `json:"owner_id"`
	Title   string `json:"title"`
	Body    string `json:"body"`
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, createNote, arg.OwnerID, arg.Title, arg.Body)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNote = `-- name: DeleteNote :execrows
DELETE FROM notes WHERE owner_id = $1 AND id = $2
`

type DeleteNoteParams struct {
	OwnerID string    `json:"owner_id"`
	ID      uuid.UUID `json:"id"`
}

func (q *Queries) DeleteNote(ctx context.Context, arg DeleteNoteParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNote, arg.OwnerID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getNote = `-- name: GetNote :one
SELECT id, owner_id, title, body, created_at, updated_at FROM notes WHERE owner_id = $1 AND id = $2
`

type GetNoteParams struct {
	OwnerID string    `json:"owner_id"`
	ID      uuid.UUID `json:"id"`
}

func (q *Queries) GetNote(ctx context.Context, arg GetNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, getNote, arg.OwnerID, arg.ID)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNotes = `-- name: ListNotes :many
SELECT id, owner_id, title, body, created_at, updated_at FROM notes
WHERE owner_id = $1
  AND (
    $2::timestamptz IS NULL
    OR (created_at, id) < ($2::timestamptz, $3::uuid)
  )
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListNotesParams struct {
	OwnerID         string             `json:"owner_id"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	PageLimit       int32              `json:"page_limit"`
}

func (q *Queries) ListNotes(ctx context.Context, arg ListNotesParams) ([]Note, error) {
	rows, err := q.db.Query(ctx, listNotes,
		arg.OwnerID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNote = `-- name: UpdateNote :one
UPDATE notes
SET title = coalesce($1, title),
    body = coalesce($2, body),
    updated_at = now()
WHERE owner_id = $3 AND id = $4
RETURNING id, owner_id, title, body, created_at, updated_at
`

type UpdateNoteParams struct {
	Title   *string   `json:"title"`
	Body    *string   `json:"body"`
	OwnerID string    `json:"owner_id"`
	ID      uuid.UUID `json:"id"`
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, updateNote,
		arg.Title,
		arg.Body,
		arg.OwnerID,
		arg.ID,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
