// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error)
	DeleteNote(ctx context.Context, arg DeleteNoteParams) (int64, error)
	GetNote(ctx context.Context, arg GetNoteParams) (Note, error)
	ListNotes(ctx context.Context, arg ListNotesParams) ([]Note, error)
	UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error)
}

var _ Querier = (*Queries)(nil)
